Repository wedidtln/sopra-project-LHD, pull requests merged in 2022-12, with the labels that each got.

#1 Implement CI for future developement
  .github/workflows/maven.yml
  .github/workflows/sonarcloud.yml
  .gitignore
  edtLHD/pom.xml
Labels: question

#50 ui improvement - little improvement
  edtLHD/src/main/java/fr/univtln/lhd/view/edt/EdtGrid.java
  edtLHD/src/main/resources/styles/edt-lhd-style.css
Labels: enhancement

#36 DAO
  .gitignore
  edtLHD/pom.xml
  edtLHD/src/main/java/fr/univtln/lhd/model/entities/dao/users/StudentDAO.java
Labels: bug, enhancement, DAO

#70 fix slotUI
  edtLHD/src/main/java/fr/univtln/lhd/view/edt/SlotUI.java
Labels: bug, JavaFx
